version: "3.9"

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Graktong1$$"  # Escaped $ with another $
      POSTGRES_DB: "main"
    volumes:
      - pg_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`postgres.nxgn.space`)"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
    networks:
      - backend
      - proxy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: allinone.gsh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Graktong123
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`admin.postgres.nxgn.space`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - backend
      - proxy

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    command: ["--host", "0.0.0.0"]
    volumes:
      - qdrant_data:/qdrant/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.nxgn.space`)"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    networks:
      - backend
      - proxy

  databases-traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.postgres.address=:5432"
    ports:
      - "80:80"
      - "5432:5432"  # PostgreSQL port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
      - proxy

volumes:
  pg_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  backend:
  proxy:
