# redis-stack-k8s.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stack
  namespace: default
spec:
  serviceName: redis-stack
  replicas: 1
  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
        - name: redis-stack
          image: redis/redis-stack:latest
          ports:
            - containerPort: 6380
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command: ["redis-server", "--port", "6380", "--loadmodule", "/opt/redis-stack/lib/rejson.so"]
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack
  namespace: default
spec:
  selector:
    app: redis-stack
  type: ClusterIP
  ports:
    - name: redis
      protocol: TCP
      port: 6380
      targetPort: 6380
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis-stack-tcp
  namespace: default
spec:
  entryPoints:
    - redis
  routes:
    - match: HostSNI(`redis.nxgn.space`)
      services:
        - name: redis-stack
          port: 6380
